service: aws-lambda-express

frameworkVersion: "2.45.2"

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 15
  stage: api
  region: us-east-2

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
